[package]
name = "cookie"
version = "0.1.11"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv_rs.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
regex.workspace = true
