name: clean ubuntu
on:
  push:
    branches:
      - master

jobs:
  clean_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: purge
        run: |
          df -h
          sudo -E apt-get purge *
          df -h
      - name: autoremove
        run: |
          df -h
          sudo -E apt-get autoremove
          df -h
      - name: autoclean
        run: |
          df -h
          sudo -E apt-get autoclean
          df -h
      - name: clean
        run: |
          df -h
          sudo -E apt-get clean
          df -h
