name: schedule test
on: 
  push: 
    branches:
      - master

jobs:
  douyu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        roomid:
          - 88080
          - 5720533
    steps:
      - name: download evina
        run: |
          wget $(curl https://api.github.com/repos/soft-cute/evina/releases/125357820/assets | jq -r .[3].browser_download_url)
          tar -xvf evina*.tar.xz
          sudo chmod +x ./evina         
      - name: cache ${{ matrix.roomid }}.conf
        id: cache-douyu
        uses: actions/cache@v3
        with:
          path: |
            ./${{ matrix.roomid }}.conf
          key: douyu-${{ matrix.roomid }}-conf

      - name: create ${{ matrix.roomid }}.conf
        if: steps.cache-douyu.outputs.cache-hit != 'true'
        run: |
          ./evina -l douyu -i > ${{ matrix.roomid }}.conf
          cat ${{ matrix.roomid }}.conf
        
