name: schedule test
on: 
  push: 
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - s390x-unknown-linux-gnu
    outputs:
      matrix: ${{ toJson(matrix) }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get matrix from build job
      id: get-matrix
      run: echo "::set-output name=matrix::${{ needs.build.outputs.matrix }}"
    - name: Use matrix in test job
      run: echo ${{ steps.get-matrix.outputs.matrix }}
