name: schedule test
on: 
  push: 
    branches:
      - master

jobs:
  douyu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        roomid:
          - 88080
          - 5720533
    steps:
      - uses: actions/checkout@v4

      - name: download evina
        run: |
          wget $(curl https://api.github.com/repos/soft-cute/evina/releases/latest | jq -r .assets[3].browser_download_url)
          tar -xvf evina*.tar.xz
          sudo chmod +x ./evina
          wget $(curl https://api.github.com/repos/BtbN/FFmpeg-Builds/releases/latest | jq -r .assets[36].browser_download_url)
          tar -xvf ffmpeg*.tar.xz
          sudo ln -s $PWD/ffmpeg-n6.0-latest-linux64-gpl-6.0/bin/ffmpeg /bin/ffmpeg



      - name: check ${{ matrix.roomid }}
        id: check_workflow
        uses: ./.github/check
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: "douyu (${{ matrix.roomid }})"
          name_step: "evina ${{ matrix.roomid }}"
          num_step: 5

      - name: evina ${{ matrix.roomid }}
        if: steps.check_workflow.outputs.in_progress == false
        run: |
          sudo ./evina -l douyu -i ${{ matrix.roomid }} -m -d douyu-${{ matrix.roomid }}

