name: schedule test
on: 
  push: 
    branches:
      - master

jobs:
  douyu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        roomid:
          - 88080
          - 5720533
    steps:
      - name: download evina
        run: |
          wget $(curl https://api.github.com/repos/soft-cute/evina/releases/125357820/assets | jq -r .[3].browser_download_url)
          tar -xvf evina*.tar.xz
          sudo chmod +x ./evina         

      - name: evina ${{ matrix.roomid }}
        run: |
          workflow_runs=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/soft-cute/test/actions/runs?status=in_progress | jq -r .)
          for workflow_run in workflow_runs; do
            if [[ $(echo $workflwd_run | jq -r .name) == "schedule test" ]];then
              jobs_url=$(echo $workflwd_run | jq -r .jobs_url)
              jobs=$(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }} $jobs_url")
              for job in jobs; do
                if [[ $(echo $job | jq -r .name) == "evina_cmd (x86_64-pc-windows-gnu)" ]];then
                  if [[ $(echo $job | jq -r .steps[5].status != "completed") ]];then
                    echo $job
                  fi
                fi
              done
            fi
          done




